// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3mKedAeabD--9Nlr_1OcPAzybyzSRpqU',
    appId: '1:846005062974:web:46214617fb976bc8c0706f',
    messagingSenderId: '846005062974',
    projectId: 'flutterfire-ui-codelab-8af55',
    authDomain: 'flutterfire-ui-codelab-8af55.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-8af55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdPBUMLDQeAom6pYz_wuP9uvy8OjuKqk',
    appId: '1:846005062974:android:a3da78f64f84287fc0706f',
    messagingSenderId: '846005062974',
    projectId: 'flutterfire-ui-codelab-8af55',
    storageBucket: 'flutterfire-ui-codelab-8af55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG0vLs64YXiPn6R1abevuB83BQyZGHhbE',
    appId: '1:846005062974:ios:70a06f61c3bfefa5c0706f',
    messagingSenderId: '846005062974',
    projectId: 'flutterfire-ui-codelab-8af55',
    storageBucket: 'flutterfire-ui-codelab-8af55.appspot.com',
    iosClientId: '846005062974-f51jh05gi4bn98b619rlnbvk9d3nddpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG0vLs64YXiPn6R1abevuB83BQyZGHhbE',
    appId: '1:846005062974:ios:70a06f61c3bfefa5c0706f',
    messagingSenderId: '846005062974',
    projectId: 'flutterfire-ui-codelab-8af55',
    storageBucket: 'flutterfire-ui-codelab-8af55.appspot.com',
    iosClientId: '846005062974-f51jh05gi4bn98b619rlnbvk9d3nddpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
